#cloud-config
users:
  - name: devops
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo
    ssh_authorized_keys:
      - ${ssh_public_key}

package_update: true
packages:
  - curl
  - docker.io
  - containerd

runcmd:
  - systemctl enable docker
  - systemctl start docker
